# Generated by Django 3.0.7 on 2020-06-10 01:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_info', models.CharField(max_length=200, verbose_name='название ')),
                ('text', models.TextField(verbose_name='Текст1')),
                ('PudDate', models.DateTimeField(verbose_name='Дата')),
            ],
        ),
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('coment', models.CharField(max_length=100, verbose_name='коментарий')),
                ('info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='camera.info')),
            ],
        ),
    ]
